// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Server.Database;

#pragma warning disable 219, 612, 618
#nullable enable

namespace Database.CompiledModels
{
    [DbContext(typeof(ServerDbContext))]
    public partial class ServerDbContextModel : RuntimeModel
    {
        static ServerDbContextModel()
        {
            var model = new ServerDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static ServerDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
